import type { Component } from "vue";

type IconLoader = () => Promise<{ default: Component }>;

export const iconLoaders: Record<string, IconLoader> = {
  ActivityIcon: () => import("lucide-vue-next/dist/esm/icons/activity.js"),
  AlertCircleIcon: () => import("lucide-vue-next/dist/esm/icons/circle-alert.js"),
  AlertTriangleIcon: () => import("lucide-vue-next/dist/esm/icons/triangle-alert.js"),
  ArrowUpDownIcon: () => import("lucide-vue-next/dist/esm/icons/arrow-up-down.js"),
  BarChart3Icon: () => import("lucide-vue-next/dist/esm/icons/bar-chart-3.js"),
  BeakerIcon: () => import("lucide-vue-next/dist/esm/icons/beaker.js"),
  BellIcon: () => import("lucide-vue-next/dist/esm/icons/bell.js"),
  BookOpenIcon: () => import("lucide-vue-next/dist/esm/icons/book-open.js"),
  BotIcon: () => import("lucide-vue-next/dist/esm/icons/bot.js"),
  BugIcon: () => import("lucide-vue-next/dist/esm/icons/bug.js"),
  CalendarIcon: () => import("lucide-vue-next/dist/esm/icons/calendar.js"),
  CheckCircleIcon: () => import("lucide-vue-next/dist/esm/icons/circle-check.js"),
  ChevronDownIcon: () => import("lucide-vue-next/dist/esm/icons/chevron-down.js"),
  ClockIcon: () => import("lucide-vue-next/dist/esm/icons/clock.js"),
  Columns3Icon: () => import("lucide-vue-next/dist/esm/icons/columns-3.js"),
  DatabaseIcon: () => import("lucide-vue-next/dist/esm/icons/database.js"),
  EditIcon: () => import("lucide-vue-next/dist/esm/icons/pencil.js"),
  EyeIcon: () => import("lucide-vue-next/dist/esm/icons/eye.js"),
  FileTextIcon: () => import("lucide-vue-next/dist/esm/icons/file-text.js"),
  FlagIcon: () => import("lucide-vue-next/dist/esm/icons/flag.js"),
  GanttChartIcon: () => import("lucide-vue-next/dist/esm/icons/gantt-chart.js"),
  GitBranchIcon: () => import("lucide-vue-next/dist/esm/icons/git-branch.js"),
  GroupIcon: () => import("lucide-vue-next/dist/esm/icons/group.js"),
  HistoryIcon: () => import("lucide-vue-next/dist/esm/icons/history.js"),
  HomeIcon: () => import("lucide-vue-next/dist/esm/icons/house.js"),
  ImageIcon: () => import("lucide-vue-next/dist/esm/icons/image.js"),
  InboxIcon: () => import("lucide-vue-next/dist/esm/icons/inbox.js"),
  KanbanIcon: () => import("lucide-vue-next/dist/esm/icons/kanban.js"),
  LayersIcon: () => import("lucide-vue-next/dist/esm/icons/layers.js"),
  LayoutDashboardIcon: () => import("lucide-vue-next/dist/esm/icons/layout-dashboard.js"),
  LayoutGridIcon: () => import("lucide-vue-next/dist/esm/icons/layout-grid.js"),
  LinkIcon: () => import("lucide-vue-next/dist/esm/icons/link.js"),
  ListChecksIcon: () => import("lucide-vue-next/dist/esm/icons/list-checks.js"),
  ListFilterIcon: () => import("lucide-vue-next/dist/esm/icons/list-filter.js"),
  ListIcon: () => import("lucide-vue-next/dist/esm/icons/list.js"),
  Maximize2Icon: () => import("lucide-vue-next/dist/esm/icons/maximize-2.js"),
  MaximizeIcon: () => import("lucide-vue-next/dist/esm/icons/maximize.js"),
  MessageSquareIcon: () => import("lucide-vue-next/dist/esm/icons/message-square.js"),
  PackageIcon: () => import("lucide-vue-next/dist/esm/icons/package.js"),
  PanelRightIcon: () => import("lucide-vue-next/dist/esm/icons/panel-right.js"),
  PinIcon: () => import("lucide-vue-next/dist/esm/icons/pin.js"),
  PlusIcon: () => import("lucide-vue-next/dist/esm/icons/plus.js"),
  SearchIcon: () => import("lucide-vue-next/dist/esm/icons/search.js"),
  SettingsIcon: () => import("lucide-vue-next/dist/esm/icons/settings.js"),
  StickyNoteIcon: () => import("lucide-vue-next/dist/esm/icons/sticky-note.js"),
  Table2Icon: () => import("lucide-vue-next/dist/esm/icons/table-2.js"),
  TargetIcon: () => import("lucide-vue-next/dist/esm/icons/target.js"),
  Trash2Icon: () => import("lucide-vue-next/dist/esm/icons/trash-2.js"),
  UserIcon: () => import("lucide-vue-next/dist/esm/icons/user.js"),
  UsersIcon: () => import("lucide-vue-next/dist/esm/icons/users.js"),
  ZapIcon: () => import("lucide-vue-next/dist/esm/icons/zap.js"),
};

export function getIconLoader(name: string): IconLoader | undefined {
  return iconLoaders[name];
}
