export const tokens = {
  surface: {
    canvas: "var(--of-surface-canvas)",
    elevated: "var(--of-surface-elevated)",
    panel: "var(--of-surface-panel)",
    muted: "var(--of-surface-muted)",
    selected: "var(--of-surface-selected)",
    workspace: "var(--of-surface-workspace)",
    workspaceRaised: "var(--of-surface-workspace-raised)",
    workspaceStrong: "var(--of-surface-workspace-strong)",
    card: "var(--of-surface-card)",
    cardHover: "var(--of-surface-card-hover)",
    divider: "var(--of-surface-divider)",
    overlay: "var(--of-surface-overlay)",
  },
  text: {
    primary: "var(--of-text-primary)",
    secondary: "var(--of-text-secondary)",
    tertiary: "var(--of-text-tertiary)",
    strong: "var(--of-text-strong)",
    inverse: "var(--of-text-inverse)",
    muted: "var(--of-text-muted)",
    placeholder: "var(--of-text-placeholder)",
  },
  border: {
    subtle: "var(--of-border-subtle)",
    strong: "var(--of-border-strong)",
    workspace: "var(--of-border-workspace)",
    active: "var(--of-border-active)",
    inverse: "var(--of-border-inverse)",
    default: "var(--of-border-default)",
    divider: "var(--of-border-divider)",
  },
  accent: {
    default: "var(--of-accent-default)",
    strong: "var(--of-accent-strong)",
    soft: "var(--of-accent-soft)",
    linkDefault: "var(--of-link-default)",
    linkHover: "var(--of-link-hover)",
    linkVisited: "var(--of-link-visited)",
  },
  elevation: {
    card: "var(--of-elevation-card)",
    cardHover: "var(--of-elevation-card-hover)",
    dropdown: "var(--of-elevation-dropdown)",
    modal: "var(--of-elevation-modal)",
    drawer: "var(--of-elevation-drawer)",
    panel: "var(--of-elevation-panel)",
    toast: "var(--of-elevation-toast)",
    contextMenu: "var(--of-elevation-context-menu)",
    popover: "var(--of-elevation-popover)",
    fixedCol: "var(--of-elevation-fixed-col)",
    overlayLg: "var(--of-elevation-overlay-lg)",
  },
} as const;

export type Tokens = typeof tokens;
